---
- name: add jenkins key
  apt_key:
    state: present
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

- name: "Set EPEL yum repository"
  apt_repository:
      filename: "{{ item.value.name }}"
      repo: "{{ item.value.url }}"
      description: "{{ item.value.description }}"
  loop:
      "{{ lookup('dict',reposU) }}"
      
- name: "Install Java and Jenkins"
  apt:
      name: "{{ item.value.name }}"
      state: present
  loop:
      "{{ lookup('dict',softwaresU) }}"
- name: "Starting jenkins"
  service:
      name: "jenkins"
      state: started
      enabled: yes
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started