apiVersion: v1
data:
  jenkins-admin-password: S0lCd1kzaWVxTmRYUFZ2NGNaS2pBMQ==
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/name: jenkins
  name: jenkins
  namespace: jenkins
type: Opaque
