apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: jenkins
  hostPath:
    path: /data/jenkins-volume/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-pv
  volumeMode: Filesystem
