---
- name: "[Java] Add OpenJDK PPA"
  apt_repository: 
    repo: 'ppa:openjdk-r/ppa'

- name: "[Java] Install OpenJDK"
  apt: 
    pkg: openjdk-{{ java_major_version }}-jdk
    state: present

- name: "[Java] Determine if JDK CA certificates directory exists"
  stat:
    path: /etc/ssl/certs/java/cacerts
  register: ca_certificates_directory

- name: "[Java] Execute post-installation script for CA certificates"
  command: /var/lib/dpkg/info/ca-certificates-java.postinst configure
  when: not ca_certificates_directory.stat.exists

- name: "[Java] Determine if 64bit architecture"
  set_fact:
    ansible_architecture: amd64
  when: ansible_architecture == "x86_64"

- name: "[Java] Set OpenJDK as the default"
  alternatives: name=java path="/usr/lib/jvm/java-{{ java_major_version }}-openjdk/jre/bin/java"