apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
        - name: dind-storage
          emptyDir: {}
      containers:
        - image: paulokinjo/jenkins:2.0.0
          name: jenkins
          resources:
            requests:
              cpu: '0.5'
              memory: '512Mi'
            limits:
              cpu: '1'
              memory: '1024Mi'
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          ports:
            - containerPort: 8080
              name: http-port
            - containerPort: 50000
              name: jnlp-port
        - name: dind
          image: docker:19.03-dind
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: '0.5'
              memory: '256Mi'
            limits:
              cpu: '1'
              memory: '512Mi'
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
