Vagrant.configure(2) do |config|

  config.vm.define "acs" do |acs|
    acs.vm.box = "generic/ubuntu2004"
    acs.vm.hostname = "acs"
    acs.vm.network "private_network", ip: "192.168.56.40"
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "generic/ubuntu2004"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.56.41"
    jenkins.vm.network "forwarded_port", guest: 80, host: 8080
  end

end