Vagrant.configure(2) do |config|

  config.vm.define "acs" do |acs|
    acs.vm.box = "generic/ubuntu2004"
    acs.vm.box_check_update = false
    acs.vm.box_version = "3.3.0"
    acs.vm.hostname = "acs"

    acs.vm.network "private_network", ip: "192.168.56.40"

    acs.vm.provider :virtualbox do |v|
      v.name = 'acs'
      v.memory = 2048
      v.cpus = 1
    end

  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "generic/ubuntu2004"
    jenkins.vm.box_check_update = false
    jenkins.vm.box_version = "3.3.0"
    jenkins.vm.hostname = "jenkins"

    jenkins.vm.network "private_network", ip: "192.168.56.41"

    jenkins.vm.provider :virtualbox do |v|
      v.name = 'jenkins'
      v.memory = 1024
      v.cpus = 1
    end
  end

end
